### PR TITLE
getting things working with the latest Swiper and Polymer libs

### PR DESCRIPTION
**Pull request by dougchestnut**
A few fixes for Polymer 2.0
Added a selected attribute to bind to
Tweaked some of the properties to match changes in the Swiper library v4

### CODE REVIEW

**Comment by rubenstolk** [comment]
Can you please fix the conflicts?

**Comment by dougchestnut** [comment]
Sorry about that, didn't notice the conflict

**Comment by rubenstolk** [comment]
Still not able to merge, perhaps open an new PR?

**Comment by dougchestnut** [comment]
Will get this working today, noticed that the keyboard option isn't working, so will fix that and open a new PR.

**Pull request closed without merging**
